import { GamePlayer, Settlement, SkippedTransfer } from '../types';
import { formatCurrency } from './calculations';

export const generateGameSummary = (
  date: string,
  players: GamePlayer[],
  settlements: Settlement[],
  skippedTransfers: SkippedTransfer[],
  chipGap?: number | null,
  chipGapPerPlayer?: number | null
): string => {
  const gameDate = new Date(date).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let summary = `🃏 *Poker Night Results*\n`;
  summary += `📅 ${gameDate}\n\n`;

  // Sort players by profit (winners first)
  const sortedPlayers = [...players].sort((a, b) => b.profit - a.profit);

  summary += `💰 *Results:*\n`;
  sortedPlayers.forEach((player, index) => {
    const emoji = player.profit > 0 ? '🟢' : player.profit < 0 ? '🔴' : '⚪';
    const medal = index === 0 && player.profit > 0 ? ' 🏆' : '';
    summary += `${emoji} ${player.playerName}: ${formatCurrency(player.profit)}${medal}\n`;
  });

  // Show chip gap adjustment if present
  if (chipGap && chipGap !== 0) {
    summary += `\n⚠️ *Chip Count Adjustment:*\n`;
    if (chipGap > 0) {
      summary += `Counted ₪${chipGap} extra • Adjusted -₪${Math.abs(chipGapPerPlayer || 0)} per player\n`;
    } else {
      summary += `Counted ₪${Math.abs(chipGap)} short • Adjusted +₪${Math.abs(chipGapPerPlayer || 0)} per player\n`;
    }
  }

  if (settlements.length > 0) {
    summary += `\n💸 *Settlements:*\n`;
    settlements.forEach(s => {
      summary += `${s.to} ← ${s.from}: ${formatCurrency(s.amount)}\n`;
    });
  }

  if (skippedTransfers.length > 0) {
    summary += `\n💡 *Note - small amounts (still to be paid):*\n`;
    skippedTransfers.forEach(s => {
      summary += `${s.to} ← ${s.from}: ${formatCurrency(s.amount)}\n`;
    });
  }

  summary += `\n_Generated by Poker Manager_ 🎲`;

  return summary;
};

export const shareToWhatsApp = (text: string): void => {
  const encoded = encodeURIComponent(text);
  window.open(`https://wa.me/?text=${encoded}`, '_blank');
};

