import { GamePlayer, Settlement, SkippedTransfer, ChipValue } from '../types';
import { formatCurrency, cleanNumber } from './calculations';

// Calculate total chips for a player
const getTotalChipsForPlayer = (player: GamePlayer, chipValues: ChipValue[]): number => {
  let total = 0;
  for (const [chipId, count] of Object.entries(player.chipCounts)) {
    const chip = chipValues.find(c => c.id === chipId);
    if (chip) {
      total += count * chip.value;
    }
  }
  return total;
};

export const generateGameSummary = (
  date: string,
  players: GamePlayer[],
  settlements: Settlement[],
  skippedTransfers: SkippedTransfer[],
  chipGap?: number | null,
  chipGapPerPlayer?: number | null,
  rebuyValue?: number,
  chipValues?: ChipValue[]
): string => {
  const gameDate = new Date(date).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let summary = `🃏 *Poker Night Results*\n`;
  summary += `📅 ${gameDate}\n\n`;

  // Sort players by profit (winners first)
  const sortedPlayers = [...players].sort((a, b) => b.profit - a.profit);

  // LTR mark to force left-to-right display in WhatsApp
  const LTR = '\u200E';
  
  summary += `💰 *Results:*\n`;
  sortedPlayers.forEach((player, index) => {
    const emoji = player.profit > 0 ? '🟢' : player.profit < 0 ? '🔴' : '⚪';
    // Add medals for top 3 positions
    let medal = '';
    if (index === 0) medal = ' 🥇';
    else if (index === 1) medal = ' 🥈';
    else if (index === 2) medal = ' 🥉';
    
    const profitText = player.profit >= 0 
      ? `+₪${cleanNumber(Math.abs(player.profit))}` 
      : `-₪${cleanNumber(Math.abs(player.profit))}`;
    
    // Add chips and rebuys info
    const totalChips = chipValues ? getTotalChipsForPlayer(player, chipValues) : 0;
    const rebuyAmount = rebuyValue ? player.rebuys * rebuyValue : 0;
    const detailsText = chipValues && rebuyValue 
      ? ` | 🎰${totalChips.toLocaleString()} | 🔄${player.rebuys}(₪${cleanNumber(rebuyAmount)})`
      : '';
    
    summary += `${LTR}${emoji} ${player.playerName}: ${profitText}${medal}${detailsText}\n`;
  });

  // Show chip gap adjustment if present
  if (chipGap && chipGap !== 0) {
    summary += `\n⚠️ *Chip Count Adjustment:*\n`;
    if (chipGap > 0) {
      summary += `Counted ₪${cleanNumber(chipGap)} extra • Adjusted -₪${cleanNumber(Math.abs(chipGapPerPlayer || 0))} per player\n`;
    } else {
      summary += `Counted ₪${cleanNumber(Math.abs(chipGap))} short • Adjusted +₪${cleanNumber(Math.abs(chipGapPerPlayer || 0))} per player\n`;
    }
  }

  if (settlements.length > 0) {
    summary += `\n💸 *Settlements:*\n`;
    settlements.forEach(s => {
      // s.from = loser (pays), s.to = winner (receives)
      summary += `${s.from} משלם ל${s.to}: ₪${cleanNumber(s.amount)}\n`;
    });
  }

  if (skippedTransfers.length > 0) {
    summary += `\n💡 *Small amounts (not mandatory):*\n`;
    skippedTransfers.forEach(s => {
      summary += `${s.from} משלם ל${s.to}: ₪${cleanNumber(s.amount)}\n`;
    });
  }

  summary += `\n_Generated by Poker Manager_ 🎲`;

  return summary;
};

export const shareToWhatsApp = (text: string): void => {
  const encoded = encodeURIComponent(text);
  window.open(`https://wa.me/?text=${encoded}`, '_blank');
};

